# Generated by Django 3.1 on 2020-11-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=240)),
                ('img_url', models.CharField(max_length=240)),
                ('category', models.CharField(max_length=64)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='my_listings',
            field=models.ManyToManyField(blank=True, related_name='users', to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='user',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='watchs', to='auctions.Listing'),
        ),
    ]
