# Generated by Django 3.1 on 2020-11-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201125_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='watch_list', to='auctions.Listing'),
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
