# Generated by Django 3.1 on 2020-11-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201125_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='listing_ids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_id', to='auctions.listing'),
        ),
    ]
