# Generated by Django 3.1 on 2020-11-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201125_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='listing_ids',
        ),
        migrations.AddField(
            model_name='watch',
            name='auction',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='auctions.listing'),
        ),
    ]
